spring:
    datasource:
        url: jdbc:postgresql://localhost:6969/security_db
        username: postgres
        password: '***'
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
            format_sql: true
    security:
#        user:
#            name: user
#            password: '***'
#            roles:
#                - ROLE_USER
#        user:
#            name: user
#            password: pass
#            roles:
#                - ADMIN




